# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'
inhibit_all_warnings!

def zd_dependencyPods
    pod 'ZDTableViewBinding', :path => '../'
    pod 'MJExtension'
    pod 'AFNetworking'
    pod 'YYModel'
    pod 'JPFPSStatus'
end

target 'Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Demo
  zd_dependencyPods

  target 'DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


post_install do |installer|
  installer.pods_project.targets.each do |target|
       target.build_configurations.each do |config|
            config.build_settings['CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF'] = 'NO'
       end
  end
end
